version: '2'
services:
    tasmobackup:
        ports:
            - '8259:80'
        volumes:
            - ./data:/var/www/html/data
        container_name: TasmoBackup
        image: 'danmed/tasmobackup'
